{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) .Values.server.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "edge-ai-car-classification.fullname" . }}-models
  labels:
  {{- include "edge-ai-car-classification.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
