deployment:
  deployment_target:
    platform: openvino
    runtime: openvino-model-server
    storage: minio
    sync_method: sidecar
  inference:
    domain: computer_vision
    input_names:
    - input
    input_shape:
    - 1
    - 3
    - 300
    - 300
    num_classes: 1000
    output_names:
    - output
    output_shape:
    - 1
    - 1000
    task: image_classification
  metadata:
    accuracy: 'Top-1: 81.6%, Top-5: 95.7%'
    created_at: '2025-08-21 14:37:06'
    dataset: ImageNet
    model_type: EfficientNet-B3
  model:
    architecture: EfficientNet-B3
    format: onnx
    framework: pytorch
    name: efficientnet_b3.onnx
    openvino_optimized: false
    size_mb: 46.59049606323242
  name: efficientnet-b3
  preprocessing:
    color_format: RGB
    input_size:
    - 300
    - 300
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  tags:
    deployment_method: kubernetes
    environment: edge-ai
    framework: PyTorch
    model_type: EfficientNet
    purpose: Image Classification
    sync_sidecar: enabled
    task: Classification
    version: B3
  version: 1.0.0
