apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file sample-compose/docker-compose.yaml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "30002"
      port: 30002
      targetPort: 80
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
