version: "3.7"
services:
    web:
        image: nginx
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M
        ports:
            - "30002:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
