version: '3'

services:
  database:
    image: postgres
    volumes:
      - volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=beersnobdb, beersnobdb_dev
      - POSTGRES_USER=mhuls
      - POSTGRES_PASSWORD=aStrongPassword
    ports:
      - 54321:5432
  frontend:
    image: nginx
    ports:
      - 30002:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80